
version: '3'
services:
  node-app:
    build: ./
    ports:
      - "4000:4000"
    depends_on:
      - mongo-db
    volumes:
      - ./volumes:/data/db

  mongo-db:
    image: mongo:latest
    container_name: mongo-container
    environment:
      - MONGODB_URI=mongodb://127.0.0.1:27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./volumes:/data/db

